on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    defaults:
      run:
        shell: bash -l {0}
    container: continuumio/anaconda3
    steps:
      - uses: actions/checkout@v3
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB.TOKEN }}
        run: |
          conda env create -f env.yaml
          conda init
          conda activate solubility-model
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master >> report.md
          cml-send-comment report.md
      # - name: Write CML report
      #   env:
      #     REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # Post reports as comments in GitHub PRs
      #     cat results.txt >> report.md
      #     cml comment create report.md
